spring:
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    cache: false
    suffix: .html
    check-template-location: true
    servlet:
      content-type: text/html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kuangstudy?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
#  redis:
#    host: 192.168.56.20
#    port: 6379
#  cache:
#    type: redis
#    redis:
#      time-to-live: 3600000
#      cache-null-values: true


logging:
  level:
    root: info
    club.codehero: debug
  file: log/blog-pro.log
server:
  port: 8085
